import { describe, expect, it } from "vitest";
import { createEmptySqlSchema, isSqlSchemaCodeBlock, parseSqlSchema, serializeSqlSchema, validateSqlSchema } from "./sqlSchema";

const SOURCE = `-- nexus-schema v1
-- title: Orders
-- layout users x=0 y=0 color=#2563eb
-- layout orders x=420 y=0 color=#16a34a
-- note table users: Customer accounts
-- note column users.email: Login address

CREATE TABLE users (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  PRIMARY KEY (id)
);

CREATE TABLE orders (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL,
  total numeric(12,2) NOT NULL DEFAULT 0
);

ALTER TABLE orders
  ADD CONSTRAINT fk_orders_user
  FOREIGN KEY (user_id) REFERENCES users(id);
`;

describe("Nexus PostgreSQL schema format", () => {
  it("parses directives, table details, and foreign keys", () => {
    const parsed = parseSqlSchema(SOURCE);
    expect(parsed).toMatchObject({ ok: true, document: { title: "Orders", tables: expect.arrayContaining([expect.objectContaining({ name: "users", description: "Customer accounts" })]), relationships: expect.arrayContaining([expect.objectContaining({ id: "fk_orders_user" })]) } });
    if (!parsed.ok) return;
    expect(parsed.document.tables[0].columns[1].description).toBe("Login address");
    expect(parsed.document.tables[1].columns[2].defaultValue).toBe("0");
  });

  it("formats visual models as readable PostgreSQL source", () => {
    const parsed = parseSqlSchema(SOURCE);
    if (!parsed.ok) throw new Error(parsed.error);
    const formatted = serializeSqlSchema(parsed.document);
    expect(formatted).toContain("-- nexus-schema v1");
    expect(formatted).toContain("CREATE TABLE users");
    expect(formatted).toContain("ALTER TABLE orders");
    expect(parseSqlSchema(formatted)).toMatchObject({ ok: true });
  });

  it("uses explicitly marked SQL fences only", () => {
    expect(isSqlSchemaCodeBlock("sql", "sqlschema")).toBe(true);
    expect(isSqlSchemaCodeBlock("sql", "")).toBe(false);
    expect(isSqlSchemaCodeBlock("json", "sqlschema")).toBe(false);
  });

  it("rejects unsupported and malformed source with a line number", () => {
    expect(parseSqlSchema("CREATE TABLE users (id uuid);")).toEqual(expect.objectContaining({ ok: false, error: expect.stringContaining("Line 1") }));
    expect(parseSqlSchema("-- nexus-schema v1\nCREATE INDEX users_email ON users(email);")).toEqual(expect.objectContaining({ ok: false, error: expect.stringContaining("Line 2") }));
    expect(parseSqlSchema("-- nexus-schema v1\n-- layout users x=bad y=0 color=#2563eb")).toEqual(expect.objectContaining({ ok: false, error: expect.stringContaining("Line 2") }));
  });

  it("accepts column names that begin with a constraint keyword", () => {
    const parsed = parseSqlSchema(`-- nexus-schema v1\n-- title: Audit\n\nCREATE TABLE audit (\n  id uuid PRIMARY KEY,\n  constraint_name text NOT NULL,\n  constraints integer,\n  unique_code text UNIQUE\n);\n`);
    if (!parsed.ok) throw new Error(parsed.error);
    expect(parsed.document.tables[0].columns.map((column) => column.name)).toEqual(["id", "constraint_name", "constraints", "unique_code"]);
    expect(parsed.document.tables[0].columns[3].unique).toBe(true);
  });

  it("still rejects real table-level constraints", () => {
    expect(parseSqlSchema("-- nexus-schema v1\nCREATE TABLE t (\n  id uuid,\n  UNIQUE (id)\n);")).toMatchObject({ ok: false });
    expect(parseSqlSchema("-- nexus-schema v1\nCREATE TABLE t (\n  id uuid,\n  CONSTRAINT pk_t PRIMARY KEY (id)\n);")).toMatchObject({ ok: false });
  });

  it("parses identity columns without polluting the type", () => {
    const parsed = parseSqlSchema(`-- nexus-schema v1
-- title: Ledger

CREATE TABLE entries (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  seq bigint GENERATED BY DEFAULT AS IDENTITY,
  note text
);
`);
    if (!parsed.ok) throw new Error(parsed.error);
    const [id, seq, note] = parsed.document.tables[0].columns;
    expect(id).toMatchObject({ type: "BIGINT", identity: "always", primaryKey: true, nullable: false });
    expect(seq).toMatchObject({ type: "bigint", identity: "byDefault", nullable: false, defaultValue: "" });
    expect(note).toMatchObject({ identity: "", nullable: true });
  });

  it("round-trips identity columns through the serializer", () => {
    const parsed = parseSqlSchema(`-- nexus-schema v1
-- title: Ledger

CREATE TABLE entries (
  id bigint GENERATED ALWAYS AS IDENTITY,
  seq bigint GENERATED BY DEFAULT AS IDENTITY
);
`);
    if (!parsed.ok) throw new Error(parsed.error);
    const formatted = serializeSqlSchema(parsed.document);
    expect(formatted).toContain("id bigint GENERATED ALWAYS AS IDENTITY NOT NULL");
    expect(formatted).toContain("seq bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL");
    const reparsed = parseSqlSchema(formatted);
    if (!reparsed.ok) throw new Error(reparsed.error);
    expect(reparsed.document.tables[0].columns.map((column) => column.identity)).toEqual(["always", "byDefault"]);
  });

  it("rejects identity variants outside the subset", () => {
    expect(parseSqlSchema("-- nexus-schema v1\nCREATE TABLE t (\n  id bigint GENERATED ALWAYS AS IDENTITY (START WITH 5)\n);")).toMatchObject({ ok: false });
    expect(parseSqlSchema("-- nexus-schema v1\nCREATE TABLE t (\n  total numeric GENERATED ALWAYS AS (1) STORED\n);")).toMatchObject({ ok: false });
    expect(parseSqlSchema("-- nexus-schema v1\nCREATE TABLE t (\n  id bigint GENERATED ALWAYS AS IDENTITY DEFAULT 5\n);")).toMatchObject({ ok: false });
  });

  it("starts new documents as PostgreSQL source models", () => {
    const source = serializeSqlSchema(createEmptySqlSchema());
    expect(source).toContain("-- nexus-schema v1");
    expect(validateSqlSchema(createEmptySqlSchema())).toEqual([]);
  });
});
